name: Publish

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Publish
      env:
        PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
      shell: pwsh
      run: .\build.ps1 -Bootstrap -Task Publish -NuGetApiKey $env:NUGET_KEY